[package]
name = "timescale_analytics"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg12"]
pg10 = ["pgx/pg10"]
pg11 = ["pgx/pg11"]
pg12 = ["pgx/pg12"]
pg_test = []

[dependencies]
pgx = "=0.1.19"
pgx-macros = "=0.1.19"
tdigest = {path="../crates/t-digest", features = ["use_serde"]}
hyperloglog = {path="../crates/hyperloglog"}
uddsketch = {path="../crates/udd-sketch"}

bincode = "1.3.1"
serde = "1.0"
serde_json = "1.0"
paste = "1.0"


[dependencies.flat_serialize]
git = "https://github.com/JLockerman/flat_serialize"
rev = "41c100c"

[dependencies.flat_serialize_macro]
git = "https://github.com/JLockerman/flat_serialize"
rev = "41c100c"

[dev-dependencies]
pgx-tests = "0.1.6"
