name: CI
on:
  pull_request:
  push:
    branches:
    - main
    - staging
    - trying
  schedule:
    # we build at 8am UTC, 3am Eastern, midnight Pacific
    - cron:  '0 8 * * 1-4'
  workflow_dispatch:
    inputs:
      container-image:
        description: 'Container image to pull from DockerHub'
        required: false

jobs:
  testpostgres:
    name: Test Postgres
    runs-on: ubuntu-20.04
    container:
      image: ${{ inputs.container-image || 'timescaledev/toolkit-builder:debian-11-amd64' }}
      # TODO move to image
      options: -u postgres
    strategy:
      matrix:
        pgversion: [12, 13, 14]
    env:
      # TODO Why?  Cargo default is to pass `-C incremental` to rustc; why don't we want that?
      #   https://doc.rust-lang.org/rustc/codegen-options/index.html#incremental
      #   Well turning it off takes the extension target size down from 3G to 2G...
      CARGO_INCREMENTAL: 0
      # TODO Why?  If we're concerned about trouble fetching crates, why not
      #  just fetch them once at the time we select a dependency?
      #  Errors fetching crates are probably rare enough that we don't see the
      #  need to bother, but then why not just let the build fail?
      CARGO_NET_RETRY: 10
      # TODO What reads this?  It's not listed on
      #  https://doc.rust-lang.org/cargo/reference/environment-variables.html
      CI: 1
      RUST_BACKTRACE: short

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    # TODO After the container image contains a primed target dir, is this still worth it?
    #   Only possible advantage is this one is per-pg-version but what's the impact?
    - name: Cache cargo target dir
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-test-pg${{ matrix.pgversion }}-target-${{ hashFiles('Cargo.lock', '.github/workflows/ci.yml') }}
        restore-keys: ${{ runner.os }}-test-pg${{ matrix.pgversion }}-target-

    - name: Run pgx tests
      run: tools/gharun tools/build -pg${{ matrix.pgversion }} test-extension

    # TODO post-install + doc test adds a good 90s.  We could probably put
    # them together run serially in a separate job to shave that 90s off the
    # long pole.
    - name: Run post-install tests
      run: tools/gharun tools/build -pg${{ matrix.pgversion }} test-post-install

    - name: Run doc tests
      run: tools/gharun tools/build -pg${{ matrix.pgversion }} test-doc

  testcrates:
    name: Test Crates
    runs-on: ubuntu-20.04
    container:
      image: ${{ inputs.container-image || 'timescaledev/toolkit-builder:debian-11-amd64' }}
      env:
        CARGO_INCREMENTAL: 0
        CARGO_NET_RETRY: 10
        CI: 1
        RUST_BACKTRACE: short
      options: -u postgres

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Cache cargo target dir
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-test-crates-target-${{ hashFiles('Cargo.lock', '.github/workflows/ci.yml') }}
        restore-keys: ${{ runner.os }}-test-crates-target-

    - name: Run Crates Tests
      run: tools/gharun tools/build test-crates

  testupdates:
    name: Test Updates
    runs-on: ubuntu-20.04
    container:
      image: ${{ inputs.container-image || 'timescaledev/toolkit-builder:debian-11-amd64' }}
      env:
        PGVERSION: 14

        CARGO_INCREMENTAL: 0
        CARGO_NET_RETRY: 10
        CI: 1
        RUST_BACKTRACE: short
      options: -u postgres

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Cache cargo target dir
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-test-updates-target-${{ hashFiles('Cargo.lock', '.github/workflows/ci.yml') }}
        restore-keys: ${{ runner.os }}-test-crates-target-

    # TODO Drop this.
    - name: Cache old versions dir
      uses: actions/cache@v3
      with:
        path: old-versions
        key: ${{ runner.os }}-test-old-versions-${{ hashFiles('Cargo.lock', '.github/workflows/ci.yml') }}
        restore-keys: ${{ runner.os }}-test-old-versions-

    - name: Run binary update tests
      # TODO We've always tested only one postgres version here.  We test them all at release
      #  time anyway.  If we want to test them here, too, let's make it less slow first.
      run: OS_NAME=debian OS_VERSION=11 tools/gharun tools/testbin -version no -bindir / -dbroot /tmp/db -pgport 28800 -pgversions 14 ci

    - name: Check tools/testbin
      run: sh tools/testbin check-control
