name: CI
on:
  pull_request:
  push:
    branches:
    - main
    - staging
    - trying
  schedule:
    # we build at 8am UTC, 3am Eastern, midnight Pacific
    - cron:  '0 8 * * 1-4'
  workflow_dispatch:
    inputs:
      container-image:
        description: 'Container image to pull from DockerHub'
        required: false

jobs:
  testupdates:
    name: Test Updates
    runs-on: ubuntu-20.04
    container:
      image: ${{ inputs.container-image || 'timescaledev/rust-pgx:latest' }}
      env:
        PGVERSION: 14

        CARGO_INCREMENTAL: 0
        CARGO_NET_RETRY: 10
        CI: 1
        RUST_BACKTRACE: short
        RUSTUP_MAX_RETRIES: 10

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: chown Repository
      run: chown -R postgres .

    - name: Cache cargo directories
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/cargo/registry
          /usr/local/cargo/git
        key: ${{ runner.os }}-test-updates-cargo-1.12.0
        restore-keys: ${{ runner.os }}-test-crates-cargo-1.11.0

    - name: Cache cargo target dir
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-test-updates-target-1.12.0
        restore-keys: ${{ runner.os }}-test-crates-target-1.11.0

    - name: Cache old versions dir
      uses: actions/cache@v2
      with:
        path: old-versions
        key: ${{ runner.os }}-test-old-versions-1.12.0
        restore-keys: ${{ runner.os }}-test-old-versions-1.11.0

    - name: Run Update Tests
      run: su postgres -c 'OS_NAME=debian OS_VERSION=10 tools/testbin -version no -bindir / -dbroot /tmp/db -pgport 28800 ci 2>&1'

    - name: Check tools/testbin
      run: sh tools/testbin check-control
