name: Build CI Image

on:
  pull_request:
    paths:
      - 'docker/ci/**'
      - '.github/workflows/ci_image_build.yml'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Push image to DockerHub with these tags (change testing to latest to enable)'
        required: false
        default: timescaledev/rust-pgx:testing

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-ci-buildx-debian-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ci-buildx-debian

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ORG_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: .
          file: ./docker/ci/Dockerfile
          tags: timescaledev/rust-pgx:latest

      - name: Push
        id: image_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./docker/ci/Dockerfile
          tags: ${{ inputs.tags }}

      - name: Image digest
        run: echo ${{ steps.image_build.outputs.digest }}
