name: Clippy and rustfmt
on:
  pull_request:
  push:
    branches:
    - main
    - staging
    - trying
  schedule:
    # we build at 8am UTC, 3am Eastern, midnight Pacific
    - cron:  '0 8 * * 1-4'
  workflow_dispatch:

jobs:
  clippy:
    name: Clippy/rustfmt Test
    runs-on: ubuntu-20.04
    container:
      image: timescaledev/rust-pgx:latest
      env:
        # TODO: See TODOs on duplicate block in ci.yml
        CARGO_INCREMENTAL: 0
        CARGO_NET_RETRY: 10
        CI: 1
        RUST_BACKTRACE: short
        RUSTUP_MAX_RETRIES: 10

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: chown Repository
      run: chown -R postgres .

    - name: Cache cargo directories
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/cargo/registry
          /usr/local/cargo/git
        key: ${{ runner.os }}-clippy-cargo-1.12.0
        restore-keys: ${{ runner.os }}-clippy-cargo-1.11.0

    - name: Cache cargo target dir
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-clippy-target-1.12.0
        restore-keys: ${{ runner.os }}-clippy-target-1.11.0

    - name: Run Clippy
      # Github captures stdout and stderr separately and then intermingles them
      # in the wrong order.  We don't actually care to distinguish, so redirect
      # stderr to stdout so we get the proper order.
      run: su postgres -c 'sh tools/build clippy 2>&1'

    - name: Verify formatting
      # TODO Stop adding rustfmt component when we fix our image?  Or not:  it's a harmless no-op.
      run: rustup component add rustfmt && cargo fmt --check
