name: Clippy
on:
  pull_request:
  push:
    branches:
    - main
    - staging
    - trying
  schedule:
    # we build at 8am UTC, 3am Eastern, midnight Pacific
    - cron:  '0 8 * * 1-4'
  workflow_dispatch:

jobs:
  clippy:
    name: Clippy Test
    runs-on: ubuntu-latest
    container:
      image: timescaledev/rust-pgx:latest
      env:
        # TODO: See TODOs on duplicate block in ci.yml
        # Must keep in sync with `path: target` in "Cache cargo target dir" job
        CARGO_TARGET_DIR_NAME: target
        CARGO_INCREMENTAL: 0
        CARGO_NET_RETRY: 10
        CI: 1
        RUST_BACKTRACE: short
        RUSTUP_MAX_RETRIES: 10

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get specific changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v23
      with:
        files: |
          **/*.rs

    - name: chown Repository
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: chown -R postgres .

    - name: Cache cargo directories
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/cargo/registry
          /usr/local/cargo/git
        key: ${{ runner.os }}-clippy-cargo-1.7
        restore-keys: ${{ runner.os }}-clippy-cargo-PREVIOUS

    - name: Cache cargo target dir
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-clippy-target-1.7
        restore-keys: ${{ runner.os }}-clippy-target-PREVIOUS

    - name: Run Clippy
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      # Github captures stdout and stderr separately and then intermingles them
      # in the wrong order.  We don't actually care to distinguish, so redirect
      # stderr to stdout so we get the proper order.
      run: su postgres -c 'sh tools/build clippy 2>&1'
